import { type NextPage } from "next";
import Head from "next/head";
import { Sidebar } from "~/components/Sidebar/Sidebar";
import { Logo } from "~/components/svg/Logo";
import { api } from "~/utils/api";
import { Chat } from "~/components/Main/Chat/Chat";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPCddjjjj889" });
  const foo = api.testing.goodbye.useQuery({
    number: 333,
    text: "foo bar 678999",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen">
        <div className="flex w-full max-w-xs flex-col bg-gray-50 p-5">
          <Logo />
          <div className="mt-2 border-b-2 border-neutral-700" />

          <Sidebar />
        </div>
        <div className="w-full border-l-2 border-gray-950 bg-gray-50 p-5">
          <Chat />
        </div>
      </main>
    </>
  );
};

export default Home;
